### ISSUE TITLE
external-data should be moved to data-raw

### ISSUE THREAD

**Issue by novica** [discindo/newscatcheR#14]
as discussed here: https://r-pkgs.org/data.html

Often, the data you include in data/ is a cleaned up version of raw data you’ve gathered from elsewhere. I highly recommend taking the time to include the code used to do this in the source version of your package. This will make it easy for you to update or reproduce your version of the data. I suggest that you put this code in data-raw/. You don’t need it in the bundled version of your package, so also add it to .Rbuildignore. Do all this in one step with:

**Comment by KKulma** [comment]
I'm on it!
How was the original dataset collected?

**Comment by novica** [comment]
Hi @KKulma 
the original dataset is from the python package. They store it in a sqlite database.

**Comment by novica** [comment]
Thanks @KKulma
