### ISSUE TITLE
tidyRSS & dplyr 1.0.0

### ISSUE THREAD

**Issue by RobertMyles** [discindo/newscatcheR#6]
Hi,

Sorry for opening an issue, not an issue as such, but just to let you know there are quite a few changes in the latest versions of tidyRSS, inclduing a hard dependency on dplyr 1.0.0., in case you start seeing errors all over the place.

Rob

**Comment by novica** [comment]
Hi Rob, 

Thanks for letting me know.

**Comment by novica** [comment]
Hi Rob, I hope you don't mind me opening this issue. I got an email from CRAN saying that there are errors in the package:

```
Error: get_headlines works (@test-get_headlines.R#6) --------------------
  Argument 1 must have names.
  Backtrace:
    1. newscatcheR::get_headlines("news.ycombinator.com")
    2. newscatcheR::get_news(website)
    3. tidyRSS::tidyfeed(news_source)
    4. tidyRSS:::rss_parse(response, list, clean_tags, parse_dates)
    5. tidyRSS:::clean_up(entries, "rss", clean_tags, parse_dates)
   13. purrr::map_df(...)
   14. dplyr::bind_rows(res, .id = .id)
```

Is this related to what you are saying? 

I don't actually know how to fix this. I would appreciate some help if you can.

**Comment by RobertMyles** [comment]
Hi @novica have you tried updating tidyRSS and dplyr? That is an error coming from dplyr, specifically from vctrs I think, which is being strict about an argument. I'd say updating dplyr and tidyRSS should fix it.

**Comment by novica** [comment]
Yes I think I have the latest versions:

```
> packageVersion("tidyRSS")
[1] ‘2.0.2’
> packageVersion("dplyr")
[1] ‘1.0.0’
```
But this is not an error coming from my machine. It's from CRAN [check](https://cran.r-project.org/web/checks/check_results_newscatcheR.html) about which I was notified that I need to fix.

**Comment by RobertMyles** [comment]
Does the version on CRAN have these updated dependencies? 

Works fine with tidyRSS:

```r
> tidyRSS::tidyfeed("https://news.ycombinator.com/rss")
GET request successful. Parsing...

# A tibble: 30 x 10
   feed_title feed_link feed_description feed_pub_date       item_title
   <chr>      <chr>     <chr>            <dttm>              <chr>     
 1 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 SimRefine…
 2 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 Mental We…
 3 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 The Beaut…
 4 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 First pho…
 5 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 A History…
 6 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 DeepFaceD…
 7 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 Germany, …
 8 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 Signal ap…
 9 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 The Go Co…
10 Hacker Ne… https://… Links for the i… 2020-06-05 03:20:32 Why Sleep…
# … with 20 more rows, and 5 more variables: item_link <chr>,
#   item_description <chr>, item_pub_date <dttm>, item_category <list>,
#   item_comments <chr>
```

**Comment by novica** [comment]
No. I didn't specify version for `tidyRSS` in the `Imports`.

So I should do that I guess.

**Comment by RobertMyles** [comment]
Yeah, it might solve it if you go to the latest version. Hope so :-)

**Comment by novica** [comment]
Hi Rob, 

I did some updates on the repository and now r-hub returns a completely different error which I don't think is related to dplyr and tidyRSS.  I will just wait for all the Windows tests to pass I guess.

I asked people to install it on windows and mac and one user go this when running `get_headlines()`:

```
Warning message:
Predicate functions must be wrapped in `where()`.  # Bad
  data %>% select(is.character)  # Good
  data %>% select(where(is.character))ℹ Please update your code.
This message is displayed once per session.
```

I am guessing this comes from tidyRSS? 
Probably not to relevant, but I just want to understand what's going on.

Thank you for your help.

**Comment by RobertMyles** [comment]
Hi @novica , this is a warning from dplyr, specifically from tidyselect, I believe. It's happening in tidyRSS, but it's just a warning, so I'll fix it in a future version.

**Comment by novica** [comment]
Hi @RobertMyles 

Thank a lot for your help. Closing this now.

BTW, I visited your site and saw that we come from a similar background in education. :)
